services:
  # PostgreSQL Database
  postgres:
    image: postgres:18-alpine
    container_name: porraza_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME:-porraza_db}
      POSTGRES_USER: ${DB_USER:-root}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-root}
      POSTGRES_INITDB_ARGS: "-E UTF8 --locale=en_US.UTF-8"
      TZ: Europe/Madrid
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - porraza_network
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${DB_USER:-root} -d ${DB_NAME:-porraza_db}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  # NestJS Backend Application
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: porraza_backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: ${PORT:-3001}
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ${DB_NAME:-porraza_db}
      DB_USER: ${DB_USER:-root}
      DB_PASSWORD: ${DB_PASSWORD:-root}
      JWT_SECRET: ${JWT_SECRET}
      JWT_ACCESS_EXPIRATION: ${JWT_ACCESS_EXPIRATION:-15m}
      JWT_REFRESH_EXPIRATION: ${JWT_REFRESH_EXPIRATION:-7d}
      COOKIE_DOMAIN: ${COOKIE_DOMAIN:-localhost}
      RESEND_API_KEY: ${RESEND_API_KEY}
      FRONTEND_URL: ${FRONTEND_URL:-http://localhost:3000}
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS:-http://localhost:3000}
      STRIPE_PUBLISHABLE_KEY: ${STRIPE_PUBLISHABLE_KEY}
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET}
      STRIPE_PRICE_ID: ${STRIPE_PRICE_ID}
    ports:
      - "${PORT:-3001}:3001"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - porraza_network
    healthcheck:
      test:
        [
          "CMD-SHELL",
          'node -e "require(''http'').get(''http://localhost:3001'', (res) => { process.exit(res.statusCode === 200 ? 0 : 1); });"',
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Nginx Reverse Proxy (HTTPS with Let's Encrypt)
  nginx:
    image: nginx:alpine
    container_name: porraza_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # Nginx configuration
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      # Let's Encrypt certificates (mounted from host)
      - /etc/letsencrypt:/etc/letsencrypt:ro
      # ACME challenge directory for certificate validation
      - /var/www/certbot:/var/www/certbot:ro
    depends_on:
      - backend
    networks:
      - porraza_network

volumes:
  postgres_data:
    driver: local

networks:
  porraza_network:
    driver: bridge
